name = "simply-vless"
compatibility_date = "2023-10-30"

[env.production]
name = "simply-vless"
routes = [
  { pattern = "simply-vless.katahiranaruse-daydream.workers.dev", zone_name = "katahiranaruse-daydream.workers.dev" }
]
[vars]
UUID = "9d166b44-f286-4906-8fac-5a6a7b8c6f66"
